/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 orang.glb --transform 
Files: orang.glb [3.39MB] > D:\PORTOFOLIO\Portfolio\public\3d\orang-transformed.glb [2.04MB] (40%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/orang-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.034']} position={[0.259, 5.994, -0.375]} rotation={[2.998, -1.004, 3.02]} scale={1.036} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.PaletteMaterial001} position={[0.259, 5.994, -0.375]} rotation={[2.998, -1.004, 3.02]} scale={1.036} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.033']} position={[-1.135, 5.729, -0.421]} rotation={[2.998, -1.004, 3.02]} scale={0.385} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[0.598, 3.959, -0.122]} rotation={[Math.PI, -0.343, Math.PI]} scale={[0.737, 0.737, 1.068]} />
    </group>
  )
}

useGLTF.preload('/orang-transformed.glb')
