/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot.glb --transform 
Files: robot.glb [2.24MB] > D:\PORTOFOLIO\Portfolio\public\3d\robot-transformed.glb [2.06MB] (8%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/robot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.096, 8.383, 0.304]} rotation={[Math.PI, -0.93, Math.PI]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial004} position={[1.945, 5.31, 1.711]} rotation={[2.89, -0.915, 2.941]} scale={1.252} />
    </group>
  )
}

useGLTF.preload('/robot-transformed.glb')
