/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 kevin.glb --transform 
Files: kevin.glb [842.53KB] > D:\PORTOFOLIO\Portfolio\public\3d\kevin-transformed.glb [832KB] (1%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kevin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BezierCurve.geometry} material={materials.PaletteMaterial001} position={[-0.069, 0.144, -0.071]} rotation={[0.222, 0.204, 1.436]} scale={0.062} />
      <group position={[0.014, 0.562, 0.114]} rotation={[0.325, -0.601, 0.365]} scale={[0.012, 0.023, 0.022]}>
        <mesh geometry={nodes.Mesh.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials['Material.020']} />
      </group>
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.019']} position={[0.015, 0.543, 0.114]} rotation={[0.325, -0.601, 0.365]} scale={[0.011, 0.021, 0.021]} />
      <group position={[0.112, 0.063, -0.019]} rotation={[0.62, 1.161, -0.316]} scale={[0.023, 0.017, 0.023]}>
        <mesh geometry={nodes.Mesh_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials['Material.009']} />
      </group>
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.PaletteMaterial002} position={[-0.04, 0.835, 0.081]} rotation={[1.549, 0.058, 0.353]} scale={[0.045, 0.007, 0.045]} />
      <instancedMesh args={[nodes.Cylinder011.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Cylinder011.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/kevin-transformed.glb')
